### ISSUE TITLE
Unexpected token error when installing globally via npm

### ISSUE THREAD

**Issue by hglattergotz** [reactivepod/fido#9]
When installing the package via npm ```npm install -g @reactive/fido``` the following error occurs when executing:
```bash
/Users/user/.nvm/versions/io.js/v1.6.4/lib/node_modules/@reactive/fido/index.js:5
function fido(config, page = 1, fromDate = null) {
                           ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:393:25)
    at Module._extensions..js (module.js:428:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/.nvm/versions/io.js/v1.6.4/lib/node_modules/@reactive/fido/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/Users/user/.nvm/versions/io.js/v1.6.4/lib/node_modules/@reactive/fido/bin/cli.js:5:14)
    at Module._compile (module.js:410:26)
```

Tested on node versions 4 and 1.6, same result

When cloning the repository and then linking via ```npm link``` it works fine.

**Comment by kahlil** [comment]
This is fixed, we just needed a babel register in the index.js because it is the default entry file I guess.
